### PR TITLE
Fix for multiple middle names that were being reversed

### LINKED ISSUE #10: Multiple middle names get reversed
P/R coming soon, I discovered this issue earlier when I was trying to parse a name that had multiple middle names.

So a name like `Tommy A B Lee` would come back with a `middleName: 'B A'` when it should have had `middleName: 'A B'`

p.s. Thanks for a very helpful module.

### PR DESCRIPTION
**Pull request by barwin**
Fixes #10

### CODE REVIEW

**Comment by chovy** [comment]
Can you verify this works on some of the compound last names like "Jimmy Van Husen" or whatever is in the tests?

**Comment by barwin** [comment]
Hey @chovy,

Good call. I've added a couple tests (commit https://github.com/chovy/humanparser/pull/11/commits/75f6532) that cover that scenario.  Still passes.  Let me know if you think there are any other edges we need to test for.

Thanks

**Comment by chovy** [comment]
works for me. I'll merge this when I get home tonight if that's ok.

**Comment by barwin** [comment]
Sounds good, thanks again.

**Pull request merged**
